name: ci-fullstack-workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Run tests
        run: |
          cd backend
          npm test

      - name: Create ESLint configuration file
        run: |
          cd backend
          npx eslint --init

      - name: Install ESLint dependencies
        run: |
          cd backend
          npm install eslint-config-airbnb-base eslint-plugin-import --save-dev

      - name: Run ESLint
        run: |
          cd backend
          npm run lint

      - name: Console message at completion
        run: |
          echo "Hello ${{ github.actor }}. You pushed to ${{ github.repository }} at $(date)."
