name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
        
  
# Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3
      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
    
      # Install the dependencies.
      - run: cd backend && npm ci

      # Run the tests.
      - run: cd backend && npm test

      # Clear npm cache
      - run: npm cache clean --force
      
      # Add ESLint to project as developer package
      - run: cd backend && npm install eslint --save-dev
      
      # Add airbnb to project as developer package
      - run: cd backend && npm install --save-dev eslint-config-airbnb-base
      
      # Add Prettier to project as dev package
      - run: cd backend && npm install --save-dev prettier

      # Install plugin for prettier as developer package
      - run: npm install --save-dev eslint-plugin-prettier

      # Run the linter.
      - run: cd backend && npx eslint .

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."
